import { Interfacebot } from './interfasebot';

export const Decepticons: Interfacebot[] = [
    {
        name: "Predaking",
        allegiance: "D",
        strength: 10,
        intelligence: 5,
        speed: 0,
        endurance: 8,
        rank: 7,
        courage: 9,
        firepower: 9,
        skill: 8,
        total: 56
    },
    {
        name: "Megatron",
        allegiance: "D",
        strength: 0,
        intelligence: 10,
        speed: 10,
        endurance: 10,
        rank: 10,
        courage: 9,
        firepower: 10,
        skill: 9,
        total: 78
    },
    {
        name: "Soundwave",
        allegiance: "D",
        strength: 6,
        intelligence: 9,
        speed: 8,
        endurance: 6,
        rank: 5,
        courage: 8,
        firepower: 6,
        skill: 9,
        total: 57
    },
    {
        name: "Shockwave",
        allegiance: "D",
        strength: 8,
        intelligence: 9,
        speed: 6,
        endurance: 7,
        rank: 8,
        courage: 6,
        firepower: 9,
        skill: 10,
        total: 63
    },
    {
        name: "Skywarp",
        allegiance: "D",
        strength: 6,
        intelligence: 10,
        speed: 7,
        endurance: 4,
        rank: 7,
        courage: 3,
        firepower: 9,
        skill: 10,
        total: 56,
    },
    {
        name: "testd",
        allegiance: "D",
        strength: 11,
        intelligence: 11,
        speed: 11,
        endurance: 11,
        rank: 11,
        courage: 11,
        firepower: 11,
        skill: 11,
        total: 88
    },
    {
        name: "Dr. Probious",
        allegiance: "D",
        strength: 9,
        intelligence: 4,
        speed: 8,
        endurance: 10,
        rank: 8,
        courage: 10,
        firepower: 8,
        skill: 10,
        total: 67
    },
    {
        name: "Swindle",
        allegiance: "D",
        strength: 5,
        intelligence: 8,
        speed: 6,
        endurance: 7,
        rank: 2,
        courage: 5,
        firepower: 9,
        skill: 3,
        total: 45
    },
    {
        name: "Sandstorm",
        allegiance: "D",
        strength: 7,
        intelligence: 9,
        speed: 6,
        endurance: 7,
        rank: 6,
        courage: 10,
        firepower: 6,
        skill: 9,
        total: 59
    },
    {
        name: "Blitzwing",
        allegiance: "D",
        strength: 7,
        intelligence: 7,
        speed: 8,
        endurance: 7,
        rank: 7,
        courage: 6,
        firepower: 8,
        skill: 8,
        total: 58
    },
];