import { Interfacebot } from './interfasebot';

export const Autobots: Interfacebot[] = [
    {
        name: "Optimus Prime",
        allegiance: "A",
        strength: 10,
        intelligence: 10,
        speed: 8,
        endurance: 10,
        rank: 10,
        courage: 10,
        firepower: 8,
        skill: 10,
        total: 76
    },
    {
        name: "Bumblebee",
        allegiance: "A",
        strength: 5,
        intelligence: 8,
        speed: 9,
        endurance: 5,
        rank: 5,
        courage: 10,
        firepower: 16,
        skill: 8,
        total: 56
    },
    {
        name: "Cliffjumper",
        allegiance: "A",
        strength: 4,
        intelligence: 4,
        speed: 7,
        endurance: 4,
        rank: 5,
        courage: 10,
        firepower: 7,
        skill: 5,
        total: 46
    },
    {
        name: "Jazz",
        allegiance: "A",
        strength: 6,
        intelligence: 6,
        speed: 9,
        endurance: 7,
        rank: 7,
        courage: 9,
        firepower: 6,
        skill: 5,
        total: 55
    },
    {
        name: "Ratchet",
        allegiance: "A",
        strength: 5,
        intelligence: 9,
        speed: 6,
        endurance: 7,
        rank: 5,
        courage: 10,
        firepower: 4,
        skill: 10,
        total: 56
    },
    {
        name: "Bluestreak",
        allegiance: "A",
        strength: 6,
        intelligence: 6,
        speed: 7,
        endurance: 9,
        rank: 5,
        courage: 2,
        firepower: 9,
        skill: 7,
        total: 51
    },
    {
        name: "Hubcap",
        allegiance: "A",
        strength: 3,
        intelligence: 9,
        speed: 4,
        endurance: 3,
        rank: 6,
        courage: 8,
        firepower: 1,
        skill: 9,
        total: 43
    },
    {
        name: "testa",
        allegiance: "A",
        strength: 11,
        intelligence: 11,
        speed: 11,
        endurance: 11,
        rank: 11,
        courage: 11,
        firepower: 11,
        skill: 11,
        total: 88
    },
    {
        name: "Micilan Man",
        allegiance: "A",
        strength: 10,
        intelligence: 10,
        speed: 8,
        endurance: 10,
        rank: 2,
        courage: 10,
        firepower: 8,
        skill: 10,
        total: 68
    },
    {
        name: "Bluestreak",
        allegiance: "A",
        strength: 6,
        intelligence: 6,
        speed: 7,
        endurance: 9,
        rank: 5,
        courage: 2,
        firepower: 9,
        skill: 7,
        total: 51
    },
    {
        name: "Hubcap",
        allegiance: "A",
        strength: 4,
        intelligence: 4,
        speed: 4,
        endurance: 4,
        rank: 4,
        courage: 4,
        firepower: 4,
        skill: 4,
        total: 32
    }
];